# training data
pmc_oa_image_dir  = "/mnt/data/vlmdata/PMC-OA/caption_T060_filtered_top4_sep_v0_subfigures/"
pmc_qa_image_dir  = "/mnt/data/vlmdata/PMC-QA/images/"
pmc_qa_train_csv  = "/mnt/data/vlmdata/PMC-QA/train_cleaned.csv"
pmc_qa_test_csv   = "/mnt/data/vlmdata/PMC-QA/test_cleaned.csv"
pmc_oa_jsonl       = "/mnt/data/vlmdata/PMC-OA/pmc_oa.jsonl"
pmc_oa_train_jsonl = "/mnt/data/vlmdata/PMC-OA/train.jsonl"
pmc_oa_test_jsonl  = "/mnt/data/vlmdata/PMC-OA/test.jsonl"

# eval
chexpert_images_dir  = "/mnt/data/vlmdata/CheXpert/"
chexpert_train_csv   = "/mnt/data/vlmdata/CheXpert/CheXpert-v1.0-small/train.csv"
chexpert_test_csv    = "/mnt/data/vlmdata/CheXpert/CheXpert-v1.0-small/valid.csv"
nih14_images_dir     = "/mnt/data2/vlmdata/NIH-ChestXray/data/images"
nih14_csv            = "/mnt/data2/vlmdata/NIH-ChestXray/data/Data_Entry_2017_v2020.csv"
nih14_train_val_list = "/mnt/data2/vlmdata/NIH-ChestXray/data/train_val_list.txt"
nih14_test_list      = "/mnt/data2/vlmdata/NIH-ChestXray/data/test_list.txt"
deeplesion_dir       = "/mnt/data/vlmdata/DeepLesion"
lc25000_dir          = "/mnt/data/vlmdata/lung_colon_image_set"
pcam_dir             = "/mnt/data/vlmdata/PCam"
